[colors]
[colors.primary]
background = "#000000"
foreground = "#ac9cd5"

[window]
opacity = 0.5
padding.x = 25
padding.y = 25

[colors.normal]
black   = "#000000"
red     = "#9684cc"
green   = "#ac9cd6"
yellow  = "#c8b8e6"
blue    = "#8374b9"
magenta = "#9684cc"
cyan    = "#ff7547"
white   = "#ac9cd5"

[colors.bright]
black   = "#4e3f6e"
red     = "#9684cc"
green   = "#ac9cd6"
yellow  = "#c8b8e6"
blue    = "#8374b9"
magenta = "#9684cc"
cyan    = "#ac9cd6"
white   = "#ac9cd5"

[colors.cursor]
text   = "#000000"
cursor = "#ac9cd5"
