# Background and foreground colors
background = #000000
foreground = #ded1f5
background-opacity = 0.5
window-padding-x = 25
window-padding-y = 25

# Standard colors
palette = 0=#000000
palette = 1=#9684cc
palette = 2=#ac9cd6
palette = 3=#c8b8e6
palette = 4=#8374b9
palette = 5=#9684cc
palette = 6=#ff7547
palette = 7=#ded1f5

# Bright colors
palette = 8=#4e3f6e
palette = 9=#9684cc
palette = 10=#ac9cd6
palette = 11=#c8b8e6
palette = 12=#8374b9
palette = 13=#9684cc
palette = 14=#ac9cd6
palette = 15=#ded1f5
