# panel_bg = "#FF69B4"
accent = "#ff7547" # Active Tab & Pane
overlay0 = "#4e3f6e" # Inactive pane border and auto-numbered tab text
# surface0 = "#272037" # Inactive Tab Background
# surface1 = "#FF69B4"
surface_dim = "#272037" # Space & Agent Selection Bg
overlay1 = "#5f4c85" # Custom-named inactive tab and secondary sidebar text



# panel_bg = "#FF69B4"
# surface0 = "#FF69B4"
# surface1 = "#FF69B4"
# surface_dim = "#FF69B4"
# overlay0 = "#FF69B4"
# overlay1 = "#FF69B4"
# text = "#FF69B4"
# subtext0 = "#FF69B4"
# mauve = "#FF69B4"
# green = "#FF69B4"
# yellow = "#FF69B4"
# red = "#FF69B4"
# blue = "#FF69B4"
# teal = "#FF69B4"
# peach = "#FF69B4"
