# panel_bg = "#FF69B4"
accent = "#ff7547" # Active Tab & Pane
overlay0 = "#4e3f6e" # Inactive pane border and auto-numbered tab text
# surface0 = "#272037" # Inactive Tab Background
# surface1 = "#FF69B4"
surface_dim = "#272037" # Space & Agent Selection Bg
overlay1 = "#5f4c85" # Custom-named inactive tab and secondary sidebar text



# panel_bg: Color::Reset,
# surface0: Color::Reset,
# surface1: Color::DarkGray,
# surface_dim: Color::DarkGray,
# overlay0: Color::Gray
# overlay1: Color::White,
# text: Color::Reset,
# subtext0: Color::Gray,
# mauve: Color::Gray,
# green: Color::Green,
# yellow: Color::Yellow,
# red: Color::LightRed,
# blue: Color::Blue,
# teal: Color::Cyan,
# peach: Color::Yellow,
