background            #000000
foreground            #ded1f5

background_opacity 0.6
window_padding_width 25
window_padding_height 25

# black
color0  #000000
color8  #4e3f6e

# red
color1  #9684cc
color9  #9684cc

# green
color2  #ac9cd6
color10 #ac9cd6

# yellow
color3  #c8b8e6
color11 #c8b8e6

# blue
color4  #8374b9
color12 #8374b9

# magenta
color5  #9684cc
color13 #9684cc

#cyan
color6  #ff7547
color14 #ac9cd6

#white
color7  #ded1f5
color15 #ded1f5


